# Generated by Django 5.0.2 on 2024-02-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_alter_user_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
